[build]
command = ""
publish = "web"
base = "."

# Optional: set security headers
# [[headers]]
# for = "/*"
#   [headers.values]
#   X-Content-Type-Options = "nosniff"
#   Referrer-Policy = "strict-origin-when-cross-origin"
#   X-Frame-Options = "DENY"